version: '3'

services:
  bot:
    depends_on:
      - db
    ports:
      - 5005:5005
    build:
      context: .
    command: ["-url", "${URL}", "-token", "${TOKEN}", "-mongoHost", "db"]
  proxy:
    depends_on:
      - bot
    image: nginx:mainline-alpine
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/certs
  db:
    image: mongo:3.6-xenial
    volumes:
      - db-data:/data/db

volumes:
  db-data:
